const ITEMS = [
  { id: 1, name: "Rusty Bucket", rarity: "common", category: "decoration", income: 1, bid: 15 },
  { id: 2, name: "Linen Cap", rarity: "common", category: "wearable", income: 1, bid: 12 },
  { id: 3, name: "Wooden Spoon", rarity: "common", category: "artifact", income: 1, bid: 10 },
  { id: 4, name: "Candle Stub", rarity: "common", category: "decoration", income: 1, bid: 8 },
  { id: 5, name: "Patchwork Tunic", rarity: "common", category: "wearable", income: 1, bid: 18 },
  { id: 6, name: "Clay Mug", rarity: "common", category: "decoration", income: 1, bid: 11 },
  { id: 7, name: "Hemp Sandals", rarity: "common", category: "wearable", income: 1, bid: 14 },
  { id: 8, name: "Tin Whistle", rarity: "common", category: "consumable", income: 0, bid: 9 },
  { id: 9, name: "Stone Pebble", rarity: "common", category: "artifact", income: 1, bid: 5 },
  { id: 10, name: "Worn Belt", rarity: "common", category: "wearable", income: 1, bid: 16 },
  { id: 11, name: "Dusty Scroll", rarity: "common", category: "artifact", income: 1, bid: 13 },
  { id: 12, name: "Iron Nail", rarity: "common", category: "artifact", income: 1, bid: 7 },
  { id: 13, name: "Sackcloth Banner", rarity: "common", category: "decoration", income: 1, bid: 20 },
  { id: 14, name: "Bread Crust", rarity: "common", category: "consumable", income: 0, bid: 6 },
  { id: 15, name: "Moth-Eaten Cape", rarity: "common", category: "wearable", income: 1, bid: 22 },
  { id: 16, name: "Broken Arrow", rarity: "common", category: "artifact", income: 1, bid: 10 },
  { id: 17, name: "Wicker Basket", rarity: "common", category: "decoration", income: 1, bid: 17 },
  { id: 18, name: "Salt Pouch", rarity: "common", category: "consumable", income: 0, bid: 8 },
  { id: 19, name: "Feather Quill", rarity: "common", category: "artifact", income: 1, bid: 12 },
  { id: 20, name: "Straw Hat", rarity: "common", category: "wearable", income: 1, bid: 15 },
  { id: 21, name: "Copper Ring", rarity: "uncommon", category: "artifact", income: 3, bid: 55 },
  { id: 22, name: "Leather Boots", rarity: "uncommon", category: "wearable", income: 3, bid: 65 },
  { id: 23, name: "Jade Figurine", rarity: "uncommon", category: "decoration", income: 3, bid: 72 },
  { id: 24, name: "Silk Scarf", rarity: "uncommon", category: "wearable", income: 3, bid: 58 },
  { id: 25, name: "Silver Locket", rarity: "uncommon", category: "artifact", income: 3, bid: 80 },
  { id: 26, name: "Herb Satchel", rarity: "uncommon", category: "consumable", income: 0, bid: 45 },
  { id: 27, name: "Bronze Shield", rarity: "uncommon", category: "decoration", income: 3, bid: 90 },
  { id: 28, name: "Inkwell and Pen", rarity: "uncommon", category: "artifact", income: 3, bid: 50 },
  { id: 29, name: "Wool Cloak", rarity: "uncommon", category: "wearable", income: 3, bid: 68 },
  { id: 30, name: "Stained Glass", rarity: "uncommon", category: "decoration", income: 3, bid: 62 },
  { id: 31, name: "Gear Pendant", rarity: "uncommon", category: "artifact", income: 3, bid: 75 },
  { id: 32, name: "Embroidered Gloves", rarity: "uncommon", category: "wearable", income: 3, bid: 70 },
  { id: 33, name: "Map Fragment", rarity: "uncommon", category: "consumable", income: 0, bid: 55 },
  { id: 34, name: "Brass Telescope", rarity: "uncommon", category: "decoration", income: 3, bid: 85 },
  { id: 35, name: "Enchanted Quill", rarity: "uncommon", category: "artifact", income: 3, bid: 60 },
  { id: 36, name: "Sapphire Amulet", rarity: "rare", category: "artifact", income: 8, bid: 180 },
  { id: 37, name: "Elven Cloak", rarity: "rare", category: "wearable", income: 8, bid: 220 },
  { id: 38, name: "Crystal Skull", rarity: "rare", category: "decoration", income: 8, bid: 250 },
  { id: 39, name: "Phoenix Feather", rarity: "rare", category: "consumable", income: 0, bid: 160 },
  { id: 40, name: "Runed Gauntlets", rarity: "rare", category: "wearable", income: 8, bid: 200 },
  { id: 41, name: "Meteorite Shard", rarity: "rare", category: "artifact", income: 8, bid: 280 },
  { id: 42, name: "Pixie in a Jar", rarity: "rare", category: "companion", income: 8, bid: 300 },
  { id: 43, name: "Dragon Scale", rarity: "rare", category: "decoration", income: 8, bid: 190 },
  { id: 44, name: "Void Mirror", rarity: "epic", category: "decoration", income: 20, bid: 450 },
  { id: 45, name: "Crown of Thorns", rarity: "epic", category: "wearable", income: 20, bid: 520 },
  { id: 46, name: "Phoenix Chick", rarity: "epic", category: "companion", income: 20, bid: 600 },
  { id: 47, name: "Tome of Whispers", rarity: "epic", category: "artifact", income: 20, bid: 480 },
  { id: 48, name: "Infinity Gem", rarity: "legendary", category: "artifact", income: 50, bid: 900 },
  { id: 49, name: "Celestial Armor", rarity: "legendary", category: "wearable", income: 50, bid: 1200 },
  { id: 50, name: "Elder Dragon", rarity: "legendary", category: "companion", income: 50, bid: 1500 }
];

const RARITY = {
  common: { color: "#b0b0b0", label: "Common" },
  uncommon: { color: "#4caf50", label: "Uncommon" },
  rare: { color: "#2196f3", label: "Rare" },
  epic: { color: "#9c27b0", label: "Epic" },
  legendary: { color: "#ff9800", label: "Legendary" }
};

const ITEM_BY_ID = {};
ITEMS.forEach(function(i) { ITEM_BY_ID[i.id] = i; });
function getItem(id) { return ITEM_BY_ID[id] || null; }
